using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AssetManagement.Generators
{
    [Generator]
    public class PickListIncrementalGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace AssetManagement.Core.Annotations
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Class, AllowMultiple = true)]
    public sealed class GeneratePickListAttribute : global::System.Attribute
    {
        public string PickListName { get; }
        public object[] RawItems { get; }

        public GeneratePickListAttribute(string pickListName, params object[] rawItems)
        {
            PickListName = pickListName;
            RawItems = rawItems;
        }
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource("GeneratePickListAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<PickListDefinition> pickListProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateSyntax(s),
                    transform: static (ctx, _) => GetPickListDefinition(ctx))
                .Where(static m => m != null)!;

            context.RegisterSourceOutput(pickListProvider, static (spc, pickList) => Execute(spc, pickList));
        }

        private static bool IsCandidateSyntax(SyntaxNode node)
        {
            if (node is AttributeSyntax attributeSyntax)
            {
                string name = attributeSyntax.Name.ToString();
                if (name.Contains("GeneratePickList"))
                {
                    return true;
                }
            }
            return false;
        }

        private static PickListDefinition? GetPickListDefinition(GeneratorSyntaxContext context)
        {
            AttributeSyntax attributeSyntax = (AttributeSyntax)context.Node;
            if (attributeSyntax.ArgumentList == null || attributeSyntax.ArgumentList.Arguments.Count < 1)
            {
                return null;
            }

            SemanticModel semanticModel = context.SemanticModel;
            AttributeData? attributeData = null;

            foreach (AttributeData attr in semanticModel.Compilation.Assembly.GetAttributes())
            {
                if (attr.ApplicationSyntaxReference?.GetSyntax() == attributeSyntax)
                {
                    attributeData = attr;
                    break;
                }
            }

            if (attributeData == null && attributeSyntax.Parent?.Parent is ClassDeclarationSyntax classDecl)
            {
                INamedTypeSymbol? classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (classSymbol != null)
                {
                    foreach (AttributeData attr in classSymbol.GetAttributes())
                    {
                        if (attr.ApplicationSyntaxReference?.GetSyntax() == attributeSyntax)
                        {
                            attributeData = attr;
                            break;
                        }
                    }
                }
            }

            if (attributeData == null)
            {
                return null;
            }

            if (attributeData.ConstructorArguments.Length < 1)
            {
                return null;
            }

            string? pickListName = attributeData.ConstructorArguments[0].Value?.ToString();
            if (string.IsNullOrWhiteSpace(pickListName))
            {
                return null;
            }

            List<PickListItem> items = new List<PickListItem>();

            if (attributeData.ConstructorArguments.Length > 1)
            {
                TypedConstant secondArg = attributeData.ConstructorArguments[1];
                ImmutableArray<TypedConstant> constants = secondArg.Values;
                if (!constants.IsEmpty)
                {
                    for (int i = 0; i < constants.Length - 1; i += 2)
                    {
                        int value = Convert.ToInt32(constants[i].Value);
                        string name = constants[i + 1].Value?.ToString() ?? $"Item{value}";
                        items.Add(new PickListItem(value, name));
                    }
                }
            }

            return new PickListDefinition(pickListName!, items);
        }

        private static void Execute(SourceProductionContext context, PickListDefinition pickList)
        {
            string basePascal = ToPascalCase(pickList.PickListName);
            string enumName = basePascal + "Enum";
            string className = basePascal + "PickList";
            StringBuilder source = new StringBuilder();

            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine("namespace AssetManagement.Core.Generated.PickLists");
            source.AppendLine("{");
            source.AppendLine($"    public enum {enumName}");
            source.AppendLine("    {");

            for (int i = 0; i < pickList.Items.Count; i++)
            {
                PickListItem item = pickList.Items[i];
                string identifier = ToPascalCase(item.Name);
                string suffix = i < pickList.Items.Count - 1 ? "," : "";
                source.AppendLine($"        {identifier} = {item.Value}{suffix}");
            }

            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine($"    public static class {className}");
            source.AppendLine("    {");
            source.AppendLine($"        public const string PickListName = \"{pickList.PickListName}\";");
            source.AppendLine();
            source.AppendLine("        public static class Values");
            source.AppendLine("        {");

            foreach (PickListItem item in pickList.Items)
            {
                string identifier = ToPascalCase(item.Name);
                source.AppendLine($"            public const int {identifier} = {item.Value};");
            }

            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine("        public static class Names");
            source.AppendLine("        {");

            foreach (PickListItem item in pickList.Items)
            {
                string identifier = ToPascalCase(item.Name);
                source.AppendLine($"            public const string {identifier} = \"{item.Name}\";");
            }

            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine("        public static string GetName(int value)");
            source.AppendLine("        {");
            source.AppendLine("            return value switch");
            source.AppendLine("            {");

            foreach (PickListItem item in pickList.Items)
            {
                source.AppendLine($"                {item.Value} => \"{item.Name}\",");
            }

            source.AppendLine("                _ => \"Unknown\"");
            source.AppendLine("            };");
            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine($"        public static string GetName({enumName} enumVal)");
            source.AppendLine("        {");
            source.AppendLine("            return GetName((int)enumVal);");
            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyDictionary<int, string> Items = new global::System.Collections.Generic.Dictionary<int, string>");
            source.AppendLine("        {");

            for (int i = 0; i < pickList.Items.Count; i++)
            {
                PickListItem item = pickList.Items[i];
                string suffix = i < pickList.Items.Count - 1 ? "," : "";
                source.AppendLine($"            {{ {item.Value}, \"{item.Name}\" }}{suffix}");
            }

            source.AppendLine("        };");
            source.AppendLine("    }");
            source.AppendLine("}");

            context.AddSource($"{className}.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
            {
                return "Item";
            }

            string[] words = input.Split(new[] { '_', ' ', '-' }, StringSplitOptions.RemoveEmptyEntries);
            StringBuilder sb = new StringBuilder();
            foreach (string word in words)
            {
                if (word.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(word[0]));
                    if (word.Length > 1)
                    {
                        sb.Append(word.Substring(1));
                    }
                }
            }
            return sb.ToString();
        }
    }

    public class PickListDefinition
    {
        public string PickListName { get; }
        public List<PickListItem> Items { get; }

        public PickListDefinition(string pickListName, List<PickListItem> items)
        {
            PickListName = pickListName;
            Items = items;
        }
    }

    public class PickListItem
    {
        public int Value { get; }
        public string Name { get; }

        public PickListItem(int value, string name)
        {
            Value = value;
            Name = name;
        }
    }
}
